---

- include_tasks: "check-vars.yml"

- include_tasks: "stack.yml"
  with_items:
    - stackdirs:
        - "etc/traefik/acme"
      templates:
        - src:  "traefik.toml.j2"
          name: "etc/traefik/traefik.toml"
